-- ============================================================
-- V1__init_schema.sql
-- Esquema inicial Startup CRM (PostgreSQL)
-- ============================================================

-- ============================================================
-- ROLES Y USUARIOS
-- ============================================================

CREATE TABLE rol
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        VARCHAR(100) NOT NULL,
    descripcion   VARCHAR(255),
    permisos_json TEXT
);

CREATE TABLE usuario
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        VARCHAR(255),
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    telefono      VARCHAR(50),
    rol_id        BIGINT,
    estado        VARCHAR(50),
    creado_en TIMESTAMPTZ,
    ultimo_login_en TIMESTAMPTZ,
    CONSTRAINT uk_usuario_email UNIQUE (email),
    CONSTRAINT fk_usuario_rol
        FOREIGN KEY (rol_id) REFERENCES rol (id)
);

CREATE INDEX idx_usuario_rol_id ON usuario (rol_id);


-- ============================================================
-- ETAPAS DE FUNNEL Y CLIENTE
-- ============================================================

CREATE TABLE etapa_funnel
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre     VARCHAR(255) NOT NULL,
    orden      INTEGER,
    es_default BOOLEAN      NOT NULL DEFAULT FALSE
);

-- Cliente (inferido a partir de las referencias)
CREATE TABLE cliente
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(255) NOT NULL,
    email           VARCHAR(255),
    telefono        VARCHAR(50),
    tipo            VARCHAR(50),  -- 'lead','cliente'
    estado_general  VARCHAR(50),  -- 'activo','en_seguimiento','perdido'
    etapa_funnel_id BIGINT,
    propietario_id  BIGINT,
    origen          VARCHAR(100), -- 'landing','referido','manual','import', etc.
    ultimo_contacto_en TIMESTAMPTZ,
    creado_en TIMESTAMPTZ,
    CONSTRAINT fk_cliente_etapa_funnel
        FOREIGN KEY (etapa_funnel_id) REFERENCES etapa_funnel (id),
    CONSTRAINT fk_cliente_propietario
        FOREIGN KEY (propietario_id) REFERENCES usuario (id)
);

CREATE INDEX idx_cliente_email ON cliente (email);
CREATE INDEX idx_cliente_etapa_funnel_id ON cliente (etapa_funnel_id);
CREATE INDEX idx_cliente_propietario_id ON cliente (propietario_id);


-- ============================================================
-- CANALES DE INTEGRACION Y CONVERSACIONES
-- ============================================================

CREATE TABLE canal_integracion
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo        VARCHAR(50)  NOT NULL, -- 'whatsapp','email'
    nombre      VARCHAR(255) NOT NULL,
    config_json TEXT,                  -- JSON con tokens, IDs, etc.
    activo      BOOLEAN      NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ
);

CREATE TABLE conversacion
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id            BIGINT      NOT NULL,
    canal                 VARCHAR(50) NOT NULL, -- 'whatsapp','email'
    canal_integracion_id  BIGINT,
    asunto                VARCHAR(255),
    estado                VARCHAR(50),          -- 'abierta','cerrada','pendiente'
    asignado_a_id         BIGINT,
    canal_conversation_id VARCHAR(255),
    ultimo_mensaje_en TIMESTAMPTZ,
    creado_en TIMESTAMPTZ,
    CONSTRAINT fk_conversacion_cliente
        FOREIGN KEY (cliente_id) REFERENCES cliente (id),
    CONSTRAINT fk_conversacion_canal_integracion
        FOREIGN KEY (canal_integracion_id) REFERENCES canal_integracion (id),
    CONSTRAINT fk_conversacion_asignado_a
        FOREIGN KEY (asignado_a_id) REFERENCES usuario (id)
);

CREATE INDEX idx_conversacion_cliente_id ON conversacion (cliente_id);
CREATE INDEX idx_conversacion_canal_integracion_id ON conversacion (canal_integracion_id);
CREATE INDEX idx_conversacion_asignado_a_id ON conversacion (asignado_a_id);
CREATE INDEX idx_conversacion_estado ON conversacion (estado);


-- ============================================================
-- MENSAJES
-- ============================================================

CREATE TABLE mensaje
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversacion_id      BIGINT      NOT NULL,
    canal                VARCHAR(50) NOT NULL, -- 'whatsapp','email'
    direccion            VARCHAR(10) NOT NULL, -- 'in','out'
    contenido            TEXT,                 -- cuerpo del mensaje
    fecha_envio TIMESTAMPTZ,
    estado               VARCHAR(50),          -- 'enviado','entregado','leido','error'
    remitente_usuario_id BIGINT,
    remitente_cliente_id BIGINT,
    canal_message_id     VARCHAR(255),
    idempotency_key      VARCHAR(255),
    payload_raw          TEXT,
    creado_en TIMESTAMPTZ,
    CONSTRAINT fk_mensaje_conversacion
        FOREIGN KEY (conversacion_id) REFERENCES conversacion (id),
    CONSTRAINT fk_mensaje_remitente_usuario
        FOREIGN KEY (remitente_usuario_id) REFERENCES usuario (id),
    CONSTRAINT fk_mensaje_remitente_cliente
        FOREIGN KEY (remitente_cliente_id) REFERENCES cliente (id)
);

CREATE INDEX idx_mensaje_conversacion_id ON mensaje (conversacion_id);
CREATE INDEX idx_mensaje_fecha_envio ON mensaje (fecha_envio);
CREATE UNIQUE INDEX uk_mensaje_canal_message_id ON mensaje (canal_message_id);
CREATE UNIQUE INDEX uk_mensaje_idempotency_key ON mensaje (idempotency_key);


-- ============================================================
-- TAREAS
-- ============================================================

CREATE TABLE tarea
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo          VARCHAR(255) NOT NULL,
    descripcion     TEXT,
    cliente_id      BIGINT,
    conversacion_id BIGINT,
    asignado_a_id   BIGINT,
    creado_por_id   BIGINT,
    fecha_limite    DATE,
    estado          VARCHAR(50), -- 'pendiente','en_progreso','completada','cancelada'
    prioridad       VARCHAR(20), -- 'baja','media','alta'
    recordatorio_en TIMESTAMPTZ,
    creado_en TIMESTAMPTZ,
    completada_en TIMESTAMPTZ,
    CONSTRAINT fk_tarea_cliente
        FOREIGN KEY (cliente_id) REFERENCES cliente (id),
    CONSTRAINT fk_tarea_conversacion
        FOREIGN KEY (conversacion_id) REFERENCES conversacion (id),
    CONSTRAINT fk_tarea_asignado_a
        FOREIGN KEY (asignado_a_id) REFERENCES usuario (id),
    CONSTRAINT fk_tarea_creado_por
        FOREIGN KEY (creado_por_id) REFERENCES usuario (id)
);

CREATE INDEX idx_tarea_cliente_id ON tarea (cliente_id);
CREATE INDEX idx_tarea_conversacion_id ON tarea (conversacion_id);
CREATE INDEX idx_tarea_asignado_a_id ON tarea (asignado_a_id);
CREATE INDEX idx_tarea_estado ON tarea (estado);
CREATE INDEX idx_tarea_fecha_limite ON tarea (fecha_limite);


-- ============================================================
-- ETIQUETAS Y RELACIONES
-- ============================================================

CREATE TABLE etiqueta
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre   VARCHAR(255) NOT NULL,
    color    VARCHAR(50),
    aplica_a VARCHAR(50)  NOT NULL -- 'cliente','conversacion','tarea'
);

CREATE TABLE cliente_etiqueta
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id  BIGINT NOT NULL,
    etiqueta_id BIGINT NOT NULL,
    CONSTRAINT fk_cliente_etiqueta_cliente
        FOREIGN KEY (cliente_id) REFERENCES cliente (id),
    CONSTRAINT fk_cliente_etiqueta_etiqueta
        FOREIGN KEY (etiqueta_id) REFERENCES etiqueta (id)
);

-- Evitar duplicados de etiqueta por cliente
CREATE UNIQUE INDEX uk_cliente_etiqueta_cliente_etiqueta
    ON cliente_etiqueta (cliente_id, etiqueta_id);

CREATE TABLE conversacion_etiqueta
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversacion_id BIGINT NOT NULL,
    etiqueta_id     BIGINT NOT NULL,
    CONSTRAINT fk_conversacion_etiqueta_conversacion
        FOREIGN KEY (conversacion_id) REFERENCES conversacion (id),
    CONSTRAINT fk_conversacion_etiqueta_etiqueta
        FOREIGN KEY (etiqueta_id) REFERENCES etiqueta (id)
);
CREATE UNIQUE INDEX uk_conversacion_etiqueta_conv_etiqueta
    ON conversacion_etiqueta (conversacion_id, etiqueta_id);


-- ============================================================
-- PLANTILLAS DE COMUNICACION
-- ============================================================

CREATE TABLE plantilla_comunicacion
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canal          VARCHAR(50)  NOT NULL, -- 'whatsapp','email'
    nombre         VARCHAR(255) NOT NULL,
    asunto         VARCHAR(255),
    cuerpo         TEXT,
    variables_json TEXT,
    creado_en TIMESTAMPTZ
);

CREATE INDEX idx_plantilla_canal ON plantilla_comunicacion (canal);


-- ============================================================
-- VISTAS GUARDADAS
-- ============================================================

CREATE TABLE vista_guardada
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id    BIGINT       NOT NULL,
    entidad       VARCHAR(50)  NOT NULL, -- 'cliente','conversacion','tarea'
    nombre        VARCHAR(255) NOT NULL,
    filtros_json  TEXT,
    columnas_json TEXT,
    es_publica    BOOLEAN      NOT NULL DEFAULT FALSE,
    creado_en TIMESTAMPTZ,
    CONSTRAINT fk_vista_guardada_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuario (id)
);

CREATE INDEX idx_vista_guardada_usuario_id ON vista_guardada (usuario_id);
CREATE INDEX idx_vista_guardada_entidad ON vista_guardada (entidad);


-- ============================================================
-- ACTIVIDADES (AUDITORiA LIGERA)
-- ============================================================

CREATE TABLE actividad
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id      BIGINT,
    usuario_id      BIGINT,
    conversacion_id BIGINT,
    tarea_id        BIGINT,
    tipo            VARCHAR(100) NOT NULL, -- 'cliente_creado','mensaje_enviado', etc.
    fecha TIMESTAMPTZ NOT NULL,
    metadata_json   TEXT,
    CONSTRAINT fk_actividad_cliente
        FOREIGN KEY (cliente_id) REFERENCES cliente (id),
    CONSTRAINT fk_actividad_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuario (id),
    CONSTRAINT fk_actividad_conversacion
        FOREIGN KEY (conversacion_id) REFERENCES conversacion (id),
    CONSTRAINT fk_actividad_tarea
        FOREIGN KEY (tarea_id) REFERENCES tarea (id)
);

CREATE INDEX idx_actividad_cliente_id ON actividad (cliente_id);
CREATE INDEX idx_actividad_usuario_id ON actividad (usuario_id);
CREATE INDEX idx_actividad_conversacion_id ON actividad (conversacion_id);
CREATE INDEX idx_actividad_tarea_id ON actividad (tarea_id);
CREATE INDEX idx_actividad_fecha ON actividad (fecha);
